### ISSUE TITLE
获取版本号bug

### ISSUE THREAD

**Issue by xielovedu** [FEMessage/update-popup#17]
获取版本号bug

```bash
Bad
character escape sequence (61:13)

  59 | 
  60 |   function fetchVersion() {
> 61 |     fetch('\update_popup_version.txt' + '?_=' + Date.now())
     |              ^
  62 |       .then(res => res.text())
  63 |       .then(version => {
  64 |         if (compareVersion((version || '').trim(), currentVersion)) {


 ERROR  Build failed with errors.
npm ERR! missing script: version

npm ERR! A complete log of this run can be found in:
```

**Comment by xielovedu** [comment]
报这个错， fetch('\update_popup_version.txt' + '?_=' + Date.now())

**Comment by evillt** [comment]
我需要知道一些信息，如：

你依赖的框架？nuxt|vue-cli
你的环境变量？

如果可以，不妨把日志全部贴出来

**Comment by xielovedu** [comment]
框架是vue-cli3
vue.config.js里面的publicPath = ‘/’ 时报character escape sequence这个错，非法字符串。改为‘’就好了。
另外，环境变量在.env设置的
UPDATE_POPUP_VERSION = 1.1.6

最后，想问下，环境变量我如何设置时间戳？不想每次发版本都需要手动更改版本号。

**Comment by evillt** [comment]
> 最后，想问下，环境变量我如何设置时间戳？不想每次发版本都需要手动更改版本号。

我在 #16 里有过这样的设想

我认为在环境变量 `.env` 使用动态时间戳比较麻烦；

在 api 支持上它应该是这样子：

```js
new UpdatePopup({
  timestamp: true // 使用时间戳
})
```

输出的 `txt` 文件内容为：

```bash
1.1.6.1599221130238 # 最后一个 点数是 「时间戳」
```

**Comment by xielovedu** [comment]
像vue这样的单页面应用，能支持到检测url地址变化，包含hash变化，来触发检测更新吗？

**Comment by xielovedu** [comment]
用户正在当前页面浏览的话，如果后台发布项目更新了，插件这时会在当前页面通知我不？

**Comment by evillt** [comment]
> 用户正在当前页面浏览的话，如果后台发布项目更新了，插件这时会在当前页面通知我不？

如果**一直在当前页面浏览**的话，插件设定了每小时都会去查询一次版本号。因为我们无法 **_精确_** 得知是什么时候有更新。

**Comment by xielovedu** [comment]
这里能否劫持单页面应用路由的变化来执行checker ？

**Comment by xielovedu** [comment]
另外，组件不支持我vue.config.js里面的publicPath的值为'/'吗？设置‘/’时报错Badcharacter escape sequence，设置为''就OK了。

**Comment by evillt** [comment]
> 另外，组件不支持我vue.config.js里面的publicPath的值为'/'吗？设置‘/’时报错Badcharacter escape sequence，设置为''就OK了。

我需要 debug 一下

**Comment by xielovedu** [comment]
方便加个微信或QQ 聊下具体问题吗？

**Comment by xielovedu** [comment]
const UpdatePopup = require(’update-popup')
vue.config.js里面引入UpdatePopup ，如何传自定义参数过去？

**Comment by evillt** [comment]
> const UpdatePopup = require(’update-popup')
> vue.config.js里面引入UpdatePopup ，如何传自定义参数过去？

https://github.com/FEMessage/update-popup#options
这里是设置选项

你提到的「自定义参数」指的是什么

**Comment by xielovedu** [comment]
有例子吗？我传了参数过去没效果？写法能贴下？

**Comment by evillt** [comment]
https://github.com/FEMessage/update-popup#options
这里是设置选项

```js
// vue.config.js 或者 poi.config.js
const UpdatePopup = require('@femessage/update-popup')
const config = {
  chainWebpack: config => {
    config.plugin('femessage-update-popup').use(UpdatePopup, [{
      versionFileName: 'my_version_filename.txt'
    }])
  }
}
```

---

你指的「自定义参数」是不是这个

**Comment by xielovedu** [comment]
好的

**Comment by xielovedu** [comment]
config.plugin('femessage-update-popup').use(UpdatePopup, [{
      versionFileName: 'my_version_filename.txt'
    }])
我使用这个方式还是报错，Bad character escape sequence

**Comment by evillt** [comment]
不清楚为何你会报错

![Screen Shot 2020-08-25 at 10 16 24 PM](https://user-images.githubusercontent.com/19513289/91185654-b2071600-e720-11ea-8d62-b78593a872c3.png)

![Screen Shot 2020-08-25 at 10 18 24 PM](https://user-images.githubusercontent.com/19513289/91185878-ebd81c80-e720-11ea-89e8-62202caa0d02.png)

**Comment by levy9527** [comment]
> 另外，组件不支持我vue.config.js里面的publicPath的值为'/'吗？设置‘/’时报错Badcharacter escape sequence，设置为''就OK了。

请问，你的publicPath 为何是` /`，要不试试 `./` ？或者，你到底是部署在哪个域名下、哪个ip下，写个绝对路径。

**Comment by xielovedu** [comment]
publicPath不能设置为相对路径'/'？设置打包就报错Bad character escape sequence，设置为''就OK了

**Comment by evillt** [comment]
你的系统环境是 windows 吗

**Comment by xielovedu** [comment]
是

**Comment by levy9527** [comment]
原作者没精力搞这个了。
我建议，不用纠结 `/` 的问题了，写个绝对路径就好了
