### ISSUE TITLE
像vue这样的单页面应用，能支持到检测url地址变化，包含hash变化，来触发检测更新吗？

### ISSUE THREAD

**Issue by xielovedu** [FEMessage/update-popup#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by evillt** [comment]
这个插件的目的是「不需要任何操作，当回到这个应用时弹出更新提醒」

检测 url 变化相当于是「有了操作后才弹出提醒」，因此并不符合这个插件的目的

**Comment by xielovedu** [comment]
如果，我目前正在访问项目，项目发布之后，我在当前页面没有发现弹出提醒，需要我切换tab或者切换到后台再回来才有提醒。
另外：刚才说的
const UpdatePopup = require('update-popup')
new UpdatePopup({
    timestamp: true // 使用时间戳
})
在生成的txt文件中好像没有看到时间戳生效诶

**Comment by evillt** [comment]
现在是没有「时间戳」这个功能的，所以才在 #17 贴了「feature request」的标签。

**Comment by xielovedu** [comment]
好的，后续会加的吧？
另外：这个插件适合我在当前页面操作的同时如果有更新会通知我不？

**Comment by evillt** [comment]
继续保持在 #17 讨论吧。
