### ISSUE TITLE
支持react吗

### ISSUE THREAD

**Issue by wzz5304** [FEMessage/update-popup#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 2nthony** [comment]
不太清楚你所说的 `支持 react 吗` 是什么意思。

如果是 `create-react-app` 的话可以尝试参考[这篇文章](https://zhuanlan.zhihu.com/p/163147229)最后的部分。

**Comment by wzz5304** [comment]
![image](https://user-images.githubusercontent.com/21290190/128591554-8f5836a4-45c6-40fb-9cfd-cec783a28636.png)
咋解决

**Comment by 2nthony** [comment]
检查 `update_popup_version.txt` 这个文件存不存在。你可以尝试在自己的环境 build ，查看输出文件目录，是否存在该文件。

如果有，就检查你的 host 配置 `/update_popup_version.txt` 是否指向正确。
如果没有，可能不兼容 `create-react-app` 脚手架，因为我们当初并没有考虑 `create-react-app` 。

当然你也可以自行处理，可以适当参考 `poi.js` 和 `nuxt.js` 这两个文件。

**Comment by levy9527** [comment]
支持啊。在umi.js 上实践过。不过，本地要先build，import才不会报错，线上是没有这个问题的。

![image](https://user-images.githubusercontent.com/9384365/130550133-3cb7be87-1061-40cf-a021-55b21780de05.png)


```
// vue.config.js 
// poi.config.js 
// .umirc.ts
const config = {
  chainWebpack: config => {
    config.plugin('femessage-update-popup').use(require('@femessage/update-popup'), [{auto: true}])
  }
}

// App.js
// 主要是这句话，本地开发可能报错，需要先build，或者先注释掉。而因为线上是会build再 deploy，所以线上不会有问题。
import '@femessage/update-popup/app/main'
```
