### ISSUE TITLE
请问下vue 2.0 怎么用这个呢

### ISSUE THREAD

**Issue by ff163361** [FEMessage/update-popup#36]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 2nthony** [comment]
请参考这里的使用方法 https://github.com/FEMessage/update-popup/blob/dev/README-zh.md#usage

**Comment by ff163361** [comment]
照着做了，但是没有生成update_popup_version.txt文件

**Comment by 2nthony** [comment]
能列出你的输出目录看看吗

**Comment by ff163361** [comment]
![image](https://user-images.githubusercontent.com/72600170/148494955-8d8b1b35-ec0f-4abe-abb5-c129f2a64509.png)

**Comment by 2nthony** [comment]
提供一下配置文件吧，看看你是否配置正确。

**Comment by ff163361** [comment]
![image](https://user-images.githubusercontent.com/72600170/148496670-d7caa27f-abe4-4456-9601-0ab5c304971a.png)

**Comment by ff163361** [comment]
vue 2.0 和 vue3.0 目录结构都不一样，这个组件可以用吗

**Comment by 2nthony** [comment]
`webpack.prod.conf.js`

```js
const UpdataPopup = require('@femessage/update-popup')

module.exports = {
  plugins: [
    new UpdatePopup({ auto: true })
  ]
}
```

**Comment by ff163361** [comment]
![image](https://user-images.githubusercontent.com/72600170/148710121-ee91a5a9-65c2-4096-9df5-134dc05c23ac.png)

**Comment by ff163361** [comment]
打完包还是没有

**Comment by 2nthony** [comment]
> `webpack.prod.conf.js`
> 
> ```js
> const UpdataPopup = require('@femessage/update-popup')
> 
> module.exports = {
>   plugins: [
>     new UpdatePopup({ auto: true })
>   ]
> }
> ```

参数是个 object ，不是 array ，你再尝试一下
