### ISSUE TITLE
为什么点了刷新弹窗还在那

### ISSUE THREAD

**Issue by ff163361** [FEMessage/update-popup#38]

**Comment by ff163361** [comment]
![image](https://user-images.githubusercontent.com/72600170/149082390-c0b4fb27-0b43-421a-bda7-46bfefd3b35a.png)

**Comment by ff163361** [comment]
![image](https://user-images.githubusercontent.com/72600170/149086154-1bcfe35e-6e80-48f3-94dc-3dc97d18eac8.png)
![image](https://user-images.githubusercontent.com/72600170/149086184-9c34f9fa-ad74-41a5-9ff9-71d708d2f787.png)
它把请求路径也改变了

**Comment by 2nthony** [comment]
你需要把这个环境变量也传给插件，参考options 的 'publicPath'

**Comment by ff163361** [comment]
那为什么点击刷新后弹窗还会弹出????

**Comment by ff163361** [comment]
![image](https://user-images.githubusercontent.com/72600170/149092698-ff2d405f-67db-4f41-852c-bdd041279fd9.png)
![image](https://user-images.githubusercontent.com/72600170/149092557-a47285c9-af82-4857-bac3-3310ede396ca.png)
是不是应该window.location.reload(true)不走浏览器缓存从服务器重新加载数据

**Comment by 2nthony** [comment]
你可以尝试为源码将 `reload` 的参数设为 `true` 尝试效果。

因为我们以往很多项目中不会出现你那样的问题。

**Comment by levy9527** [comment]
对于是否加参数，结论是：不需要。具体可以看文档：https://developer.mozilla.org/en-US/docs/Web/API/Location/reload

你这个问题，你需要debug一下，你是否拿到了新的静态文件。

**Comment by levy9527** [comment]
这个弹窗的本质只是，客户端的version 与 静态服务器或对象存储系统里的 version 不一致。但具体为什么刷新后还一致，你需要根据你的部署情况去分析。
