### ISSUE TITLE
@femessage/update-popup 相关依赖升级  导致无法打包

### ISSUE THREAD

**Issue by yuwangi** [FEMessage/update-popup#39]
## Describe the bug
![image](https://user-images.githubusercontent.com/13346477/188404255-91755674-c2f1-4e4d-ae6f-3794bb275136.png)

@femessage/update-popup  

dependencies   "vercel-toast": "^1.4.0"

vercel-toast默认安装最新版本  @1.6.1
![image](https://user-images.githubusercontent.com/13346477/188404791-5afe46be-4848-4c28-b7cc-5db6deced248.png)

导致报错

please  resolve,  tks~~

**Comment by 2nthony** [comment]
请提供你项目环境的更多信息，可以是：

- webpack 版本
- 用的什么框架 （ nuxt, next, ... ）
- node 版本

**Comment by hj009** [comment]
我也遇到同样的问题，之前没问题，最近编译报错。"You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file"。webpack "^4.0.0"，使用的VUE，node 14.8.0 （切换node版本无效：12.20.0和16.0.0）

**Comment by yuwangi** [comment]
- vuecli 3
- node v12.18.3  &  14.15.2  均不支持
- webpack  4.46.0

**Comment by hj009** [comment]
是包更新导致的吗  之前的环境是可用的。

**Comment by yuwangi** [comment]
依赖包更新导致的  vercel-toast

**Comment by 2nthony** [comment]
fixed in https://github.com/2nthony/vercel-toast/pull/100

尝试重新安装这个插件，确保 `vercel-toast: ^1.6.2` 。

**Comment by hj009** [comment]
用node 16.0.0  安装 "@femessage/update-popup": "^1.1.3"  即可，包含的  vercel-toast: ^1.6.2

**Comment by yuwangi** [comment]
可以了  tks~

**Comment by yuwangi** [comment]
> 用node 16.0.0 安装 "@femessage/update-popup": "^1.1.3" 即可，包含的 vercel-toast: ^1.6.2

服务器上 不能随便升级~   很多项目都在
